-- ============================================
-- 근태/휴가 관련
-- ============================================

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-att-001', '연차휴가 신청서', '연차/연차휴가 사용 시 작성하는 신청서', '근태/휴가', '<h1 style="text-align:center">연차휴가 신청서</h1><p><br></p><table><tr><th>성명</th><td></td><th>부서</th><td></td></tr><tr><th>직급</th><td></td><th>사번</th><td></td></tr></table><p><br></p><h2>휴가 정보</h2><table><tr><th>휴가 종류</th><td>☐ 연차  ☐ 하계휴가  ☐ 경조휴가  ☐ 기타 (       )</td></tr><tr><th>휴가 기간</th><td>20    년    월    일 ~ 20    년    월    일 (총     일간)</td></tr><tr><th>잔여 연차</th><td>총     일 중     일 사용 /     일 잔여</td></tr><tr><th>휴가 사유</th><td><p><br></p><p><br></p></td></tr><tr><th>비상 연락처</th><td></td></tr><tr><th>업무 대행자</th><td>부서:          성명:          </td></tr></table><p><br></p><p>위와 같이 휴가를 신청하오니 허가하여 주시기 바랍니다.</p><p><br></p><p style="text-align:center">20    년    월    일</p><p><br></p><p style="text-align:center">신청인:                 (서명)</p><p><br></p><table><tr><th>담당</th><th>팀장</th><th>부서장</th><th>대표이사</th></tr><tr><td><p><br></p><p><br></p></td><td></td><td></td><td></td></tr></table>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-att-002', '반차 신청서', '오전/오후 반차 사용 시 작성하는 신청서', '근태/휴가', '<h1 style="text-align:center">반차 신청서</h1><p><br></p><table><tr><th>성명</th><td></td><th>부서</th><td></td></tr><tr><th>직급</th><td></td><th>사번</th><td></td></tr></table><p><br></p><h2>반차 정보</h2><table><tr><th>반차 구분</th><td>☐ 오전 반차 (09:00~13:00)  ☐ 오후 반차 (14:00~18:00)</td></tr><tr><th>반차 일자</th><td>20    년    월    일 (    요일)</td></tr><tr><th>사유</th><td><p><br></p><p><br></p></td></tr><tr><th>비상 연락처</th><td></td></tr></table><p><br></p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">신청인:                 (서명)</p><p><br></p><table><tr><th>담당</th><th>팀장</th><th>부서장</th></tr><tr><td><p><br></p></td><td></td><td></td></tr></table>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-att-003', '지각/조퇴/외출 사유서', '지각, 조퇴, 외출 시 사유를 기재하는 문서', '근태/휴가', '<h1 style="text-align:center">지각/조퇴/외출 사유서</h1><p><br></p><table><tr><th>성명</th><td></td><th>부서</th><td></td></tr><tr><th>직급</th><td></td><th>사번</th><td></td></tr></table><p><br></p><h2>상세 내역</h2><table><tr><th>구분</th><td>☐ 지각  ☐ 조퇴  ☐ 외출</td></tr><tr><th>일시</th><td>20    년    월    일      시    분 ~     시    분</td></tr><tr><th>사유</th><td><p><br></p><p><br></p><p><br></p></td></tr><tr><th>증빙서류</th><td>☐ 있음 (첨부)  ☐ 없음</td></tr></table><p><br></p><p>위와 같은 사유로 보고드리오니 양해하여 주시기 바랍니다.</p><p><br></p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">작성자:                 (서명)</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-att-004', '결근 사유서', '결근 발생 시 사유를 기재하는 문서', '근태/휴가', '<h1 style="text-align:center">결근 사유서</h1><p><br></p><table><tr><th>성명</th><td></td><th>부서</th><td></td></tr><tr><th>직급</th><td></td><th>사번</th><td></td></tr></table><p><br></p><table><tr><th>결근 일자</th><td>20    년    월    일 ~ 20    년    월    일 (총     일)</td></tr><tr><th>결근 사유</th><td><p><br></p><p><br></p><p><br></p></td></tr><tr><th>증빙서류</th><td>☐ 진단서  ☐ 기타 (          )  ☐ 없음</td></tr><tr><th>향후 계획</th><td><p><br></p></td></tr></table><p><br></p><p>위와 같은 사유로 결근하였기에 사유서를 제출합니다.</p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">작성자:                 (서명)</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-att-005', '휴직 신청서', '육아휴직, 병가휴직 등 휴직 시 작성하는 신청서', '근태/휴가', '<h1 style="text-align:center">휴직 신청서</h1><p><br></p><table><tr><th>성명</th><td></td><th>부서</th><td></td></tr><tr><th>직급</th><td></td><th>사번</th><td></td></tr><tr><th>입사일</th><td></td><th>연락처</th><td></td></tr></table><p><br></p><h2>휴직 정보</h2><table><tr><th>휴직 유형</th><td>☐ 육아휴직  ☐ 병가휴직  ☐ 개인사유 휴직  ☐ 기타 (       )</td></tr><tr><th>휴직 기간</th><td>20    년    월    일 ~ 20    년    월    일 (총     개월)</td></tr><tr><th>휴직 사유</th><td><p><br></p><p><br></p><p><br></p></td></tr><tr><th>첨부 서류</th><td>☐ 진단서  ☐ 출생증명서  ☐ 기타 (          )</td></tr><tr><th>업무 인수자</th><td>부서:          성명:          </td></tr></table><p><br></p><p>위와 같이 휴직을 신청하오니 승인하여 주시기 바랍니다.</p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">신청인:                 (서명)</p><p><br></p><table><tr><th>팀장</th><th>인사팀장</th><th>대표이사</th></tr><tr><td><p><br></p><p><br></p></td><td></td><td></td></tr></table>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-att-006', '복직 신청서', '휴직 후 복직 시 작성하는 신청서', '근태/휴가', '<h1 style="text-align:center">복직 신청서</h1><p><br></p><table><tr><th>성명</th><td></td><th>부서</th><td></td></tr><tr><th>직급</th><td></td><th>사번</th><td></td></tr></table><p><br></p><table><tr><th>휴직 기간</th><td>20    년    월    일 ~ 20    년    월    일</td></tr><tr><th>휴직 유형</th><td></td></tr><tr><th>복직 예정일</th><td>20    년    월    일</td></tr><tr><th>복직 사유</th><td><p><br></p><p><br></p></td></tr><tr><th>건강 상태</th><td>☐ 양호  ☐ 치료 중 (상세:          )</td></tr></table><p><br></p><p>위와 같이 복직을 신청하오니 승인하여 주시기 바랍니다.</p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">신청인:                 (서명)</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-att-007', '출장 신청서', '국내/해외 출장 시 사전 승인을 위한 신청서', '근태/휴가', '<h1 style="text-align:center">출장 신청서</h1><p><br></p><table><tr><th>성명</th><td></td><th>부서</th><td></td></tr><tr><th>직급</th><td></td><th>사번</th><td></td></tr></table><p><br></p><h2>출장 정보</h2><table><tr><th>출장 구분</th><td>☐ 국내 출장  ☐ 해외 출장</td></tr><tr><th>출장 기간</th><td>20    년    월    일 ~ 20    년    월    일 (    박    일)</td></tr><tr><th>출장지</th><td></td></tr><tr><th>출장 목적</th><td><p><br></p><p><br></p></td></tr><tr><th>동행자</th><td></td></tr><tr><th>예상 경비</th><td>교통비:          원 / 숙박비:          원 / 기타:          원 / 합계:          원</td></tr><tr><th>업무 대행자</th><td></td></tr></table><p><br></p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">신청인:                 (서명)</p><p><br></p><table><tr><th>담당</th><th>팀장</th><th>부서장</th><th>대표이사</th></tr><tr><td><p><br></p></td><td></td><td></td><td></td></tr></table>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-att-008', '출장 보고서', '출장 완료 후 결과를 보고하는 문서', '근태/휴가', '<h1 style="text-align:center">출장 보고서</h1><p><br></p><table><tr><th>성명</th><td></td><th>부서</th><td></td></tr><tr><th>출장 기간</th><td>20    년    월    일 ~ 20    년    월    일</td></tr><tr><th>출장지</th><td></td></tr><tr><th>출장 목적</th><td></td></tr></table><p><br></p><h2>출장 내용</h2><table><tr><th>일자</th><th>방문처</th><th>주요 활동 내용</th></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr></table><p><br></p><h2>출장 성과 및 결과</h2><p><br></p><p><br></p><p><br></p><h2>후속 조치 사항</h2><p><br></p><p><br></p><h2>경비 정산</h2><table><tr><th>항목</th><th>금액</th><th>비고</th></tr><tr><td>교통비</td><td></td><td></td></tr><tr><td>숙박비</td><td></td><td></td></tr><tr><td>식비</td><td></td><td></td></tr><tr><td>기타</td><td></td><td></td></tr><tr><td><strong>합계</strong></td><td></td><td></td></tr></table><p><br></p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">작성자:                 (서명)</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-att-009', '재택근무 신청서', '재택근무 사전 승인을 위한 신청서', '근태/휴가', '<h1 style="text-align:center">재택근무 신청서</h1><p><br></p><table><tr><th>성명</th><td></td><th>부서</th><td></td></tr><tr><th>직급</th><td></td><th>사번</th><td></td></tr></table><p><br></p><table><tr><th>근무 일자</th><td>20    년    월    일 (    요일)</td></tr><tr><th>근무 시간</th><td>    시    분 ~     시    분</td></tr><tr><th>근무 장소</th><td>☐ 자택  ☐ 기타 (          )</td></tr><tr><th>신청 사유</th><td><p><br></p><p><br></p></td></tr><tr><th>당일 업무 계획</th><td><p><br></p><p><br></p><p><br></p></td></tr><tr><th>연락 가능 수단</th><td>전화:          / 메신저:          </td></tr></table><p><br></p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">신청인:                 (서명)</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-att-010', '초과근무(야근) 신청서', '야근/휴일근무 등 초과근무 시 작성하는 신청서', '근태/휴가', '<h1 style="text-align:center">초과근무 신청서</h1><p><br></p><table><tr><th>성명</th><td></td><th>부서</th><td></td></tr><tr><th>직급</th><td></td><th>사번</th><td></td></tr></table><p><br></p><table><tr><th>근무 구분</th><td>☐ 연장근무(야근)  ☐ 휴일근무  ☐ 야간근무</td></tr><tr><th>근무 일시</th><td>20    년    월    일      시    분 ~     시    분 (    시간)</td></tr><tr><th>초과근무 사유</th><td><p><br></p><p><br></p></td></tr><tr><th>업무 내용</th><td><p><br></p><p><br></p></td></tr><tr><th>보상 희망</th><td>☐ 수당 지급  ☐ 대체 휴가</td></tr></table><p><br></p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">신청인:                 (서명)</p><p><br></p><table><tr><th>팀장</th><th>부서장</th></tr><tr><td><p><br></p></td><td></td></tr></table>', 'admin-001', 1);

-- ============================================
-- 인사/채용 관련
-- ============================================

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-hr-001', '입사지원서', '채용 지원 시 작성하는 입사지원서/이력서', '인사/채용', '<h1 style="text-align:center">입 사 지 원 서</h1><p><br></p><h2>인적사항</h2><table><tr><th>성명</th><td></td><th>생년월일</th><td></td></tr><tr><th>연락처</th><td></td><th>이메일</th><td></td></tr><tr><th>주소</th><td colspan="3"></td></tr><tr><th>지원 부서</th><td></td><th>희망 연봉</th><td></td></tr></table><p><br></p><h2>학력사항</h2><table><tr><th>기간</th><th>학교명</th><th>전공</th><th>학위</th></tr><tr><td></td><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td><td></td></tr></table><p><br></p><h2>경력사항</h2><table><tr><th>기간</th><th>회사명</th><th>부서/직급</th><th>담당 업무</th></tr><tr><td></td><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td><td></td></tr></table><p><br></p><h2>자격/면허</h2><table><tr><th>취득일</th><th>자격증명</th><th>발행기관</th></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr></table><p><br></p><h2>자기소개</h2><p><br></p><p><br></p><p><br></p><p><br></p><p style="text-align:center">위 기재 사항은 사실과 다름이 없음을 확인합니다.</p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">지원자:                 (서명)</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-hr-002', '경력증명서 발급 신청서', '경력증명서 발급을 요청하는 신청서', '인사/채용', '<h1 style="text-align:center">경력증명서 발급 신청서</h1><p><br></p><table><tr><th>성명</th><td></td><th>부서</th><td></td></tr><tr><th>직급</th><td></td><th>사번</th><td></td></tr><tr><th>재직 기간</th><td colspan="3">20    년    월    일 ~ 20    년    월    일</td></tr></table><p><br></p><table><tr><th>발급 사유</th><td><p><br></p></td></tr><tr><th>제출처</th><td></td></tr><tr><th>필요 부수</th><td>    부</td></tr><tr><th>기재 희망 사항</th><td>☐ 직급  ☐ 업무내용  ☐ 연봉  ☐ 기타 (          )</td></tr></table><p><br></p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">신청인:                 (서명)</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-hr-003', '재직증명서 발급 신청서', '재직증명서 발급을 요청하는 신청서', '인사/채용', '<h1 style="text-align:center">재직증명서 발급 신청서</h1><p><br></p><table><tr><th>성명</th><td></td><th>부서</th><td></td></tr><tr><th>직급</th><td></td><th>사번</th><td></td></tr><tr><th>입사일</th><td></td><th>연락처</th><td></td></tr></table><p><br></p><table><tr><th>발급 사유</th><td>☐ 금융기관 제출  ☐ 관공서 제출  ☐ 비자 신청  ☐ 기타 (          )</td></tr><tr><th>제출처</th><td></td></tr><tr><th>필요 부수</th><td>    부</td></tr></table><p><br></p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">신청인:                 (서명)</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-hr-004', '퇴직원 (사직서)', '자발적 퇴직 의사를 전달하는 사직서', '인사/채용', '<h1 style="text-align:center">퇴 직 원</h1><p><br></p><table><tr><th>성명</th><td></td><th>부서</th><td></td></tr><tr><th>직급</th><td></td><th>사번</th><td></td></tr><tr><th>입사일</th><td></td><th>연락처</th><td></td></tr></table><p><br></p><table><tr><th>퇴직 희망일</th><td>20    년    월    일</td></tr><tr><th>퇴직 사유</th><td><p><br></p><p><br></p><p><br></p></td></tr><tr><th>인수인계 계획</th><td><p><br></p><p><br></p></td></tr><tr><th>인수인계 대상자</th><td></td></tr></table><p><br></p><p>위와 같은 사유로 퇴직하고자 하오니 허가하여 주시기 바랍니다.</p><p><br></p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">신청인:                 (서명)</p><p><br></p><table><tr><th>팀장</th><th>인사팀장</th><th>대표이사</th></tr><tr><td><p><br></p><p><br></p></td><td></td><td></td></tr></table>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-hr-005', '인사발령 통보서', '인사이동, 승진, 전보 등을 통보하는 문서', '인사/채용', '<h1 style="text-align:center">인사발령 통보서</h1><p><br></p><p style="text-align:center">다음과 같이 인사발령을 통보합니다.</p><p><br></p><table><tr><th>성명</th><td></td><th>사번</th><td></td></tr></table><p><br></p><table><tr><th>발령 구분</th><td>☐ 승진  ☐ 전보  ☐ 전직  ☐ 파견  ☐ 기타</td></tr><tr><th>발령일자</th><td>20    년    월    일</td></tr><tr><th>현 소속</th><td>부서:                직급:                </td></tr><tr><th>변경 소속</th><td>부서:                직급:                </td></tr><tr><th>발령 사유</th><td><p><br></p></td></tr></table><p><br></p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">대표이사                 (직인)</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-hr-006', '서약서 (비밀유지/경업금지)', '비밀유지, 경업금지 등에 관한 서약서', '인사/채용', '<h1 style="text-align:center">서 약 서</h1><p><br></p><p>본인은 회사에 재직하는 동안 및 퇴직 후에도 아래 사항을 준수할 것을 서약합니다.</p><p><br></p><h2>제1조 (비밀유지 의무)</h2><p>본인은 업무 수행 과정에서 취득한 회사의 영업비밀, 기술정보, 고객정보, 경영정보 등 일체의 비밀정보를 재직 중은 물론 퇴직 후에도 제3자에게 누설하거나 무단으로 사용하지 않겠습니다.</p><p><br></p><h2>제2조 (경업금지 의무)</h2><p>본인은 퇴직 후     년간 회사와 동종 또는 유사한 업종의 사업체에 취업하거나 스스로 동종 영업을 하지 않겠습니다.</p><p><br></p><h2>제3조 (손해배상)</h2><p>본인이 위 의무를 위반하여 회사에 손해를 끼친 경우, 그에 대한 손해배상 책임을 지겠습니다.</p><p><br></p><table><tr><th>성명</th><td></td></tr><tr><th>부서/직급</th><td></td></tr><tr><th>주민등록번호</th><td></td></tr><tr><th>주소</th><td></td></tr></table><p><br></p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">서약인:                 (서명/날인)</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-hr-007', '신원보증서', '입사 시 제출하는 신원보증서', '인사/채용', '<h1 style="text-align:center">신 원 보 증 서</h1><p><br></p><h2>피보증인 (입사자)</h2><table><tr><th>성명</th><td></td><th>생년월일</th><td></td></tr><tr><th>주소</th><td colspan="3"></td></tr></table><p><br></p><h2>보증인</h2><table><tr><th>성명</th><td></td><th>관계</th><td></td></tr><tr><th>생년월일</th><td></td><th>연락처</th><td></td></tr><tr><th>주소</th><td colspan="3"></td></tr><tr><th>직업</th><td></td><th>근무처</th><td></td></tr></table><p><br></p><p>본인은 위 피보증인의 신원을 보증하며, 피보증인이 귀사에 재직하는 동안 고의 또는 과실로 귀사에 손해를 끼친 경우 연대하여 배상할 것을 보증합니다.</p><p><br></p><p>보증 기간: 입사일로부터     년간</p><p><br></p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">보증인:                 (서명/날인)</p>', 'admin-001', 1);

-- ============================================
-- 경비/비용 관련
-- ============================================

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-exp-001', '지출결의서', '비용 지출 승인을 위한 결의서', '경비/비용', '<h1 style="text-align:center">지 출 결 의 서</h1><p><br></p><table><tr><th>기안일</th><td>20    년    월    일</td><th>기안자</th><td></td></tr><tr><th>부서</th><td></td><th>직급</th><td></td></tr></table><p><br></p><table><tr><th>지출 목적</th><td colspan="3"><p><br></p></td></tr><tr><th>지출 예정일</th><td>20    년    월    일</td><th>지급 방법</th><td>☐ 계좌이체  ☐ 법인카드  ☐ 현금</td></tr></table><p><br></p><h2>지출 내역</h2><table><tr><th>번호</th><th>항목</th><th>금액</th><th>비고</th></tr><tr><td>1</td><td></td><td></td><td></td></tr><tr><td>2</td><td></td><td></td><td></td></tr><tr><td>3</td><td></td><td></td><td></td></tr><tr><td>4</td><td></td><td></td><td></td></tr><tr><td colspan="2"><strong>합계</strong></td><td><strong></strong></td><td></td></tr></table><p><br></p><p>위와 같이 지출하고자 결의하오니 승인하여 주시기 바랍니다.</p><p><br></p><table><tr><th>담당</th><th>팀장</th><th>재무팀장</th><th>대표이사</th></tr><tr><td><p><br></p><p><br></p></td><td></td><td></td><td></td></tr></table>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-exp-002', '법인카드 사용 내역서', '법인카드 사용 내역을 보고하는 문서', '경비/비용', '<h1 style="text-align:center">법인카드 사용 내역서</h1><p><br></p><table><tr><th>사용자</th><td></td><th>부서</th><td></td></tr><tr><th>카드번호</th><td>****-****-****-    </td><th>보고 기간</th><td>20  년  월</td></tr></table><p><br></p><h2>사용 내역</h2><table><tr><th>No</th><th>사용일</th><th>가맹점명</th><th>사용 목적</th><th>금액</th><th>참석자</th></tr><tr><td>1</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>2</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>3</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>4</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>5</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td colspan="4"><strong>합계</strong></td><td><strong></strong></td><td></td></tr></table><p><br></p><p>※ 영수증은 별도 첨부</p><p><br></p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">작성자:                 (서명)</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-exp-003', '교통비/출장비 정산서', '교통비, 출장비 등을 정산하는 문서', '경비/비용', '<h1 style="text-align:center">교통비/출장비 정산서</h1><p><br></p><table><tr><th>성명</th><td></td><th>부서</th><td></td></tr><tr><th>정산 기간</th><td colspan="3">20    년    월    일 ~ 20    년    월    일</td></tr></table><p><br></p><h2>정산 내역</h2><table><tr><th>No</th><th>일자</th><th>출발지 → 도착지</th><th>교통수단</th><th>금액</th><th>비고</th></tr><tr><td>1</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>2</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>3</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>4</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>5</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td colspan="4"><strong>합계</strong></td><td><strong></strong></td><td></td></tr></table><p><br></p><p>※ 영수증 및 증빙 자료를 첨부해 주시기 바랍니다.</p><p><br></p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">신청인:                 (서명)</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-exp-004', '경조사비 신청서', '경조사 발생 시 경조금을 신청하는 문서', '경비/비용', '<h1 style="text-align:center">경조사비 신청서</h1><p><br></p><table><tr><th>성명</th><td></td><th>부서</th><td></td></tr><tr><th>직급</th><td></td><th>사번</th><td></td></tr></table><p><br></p><table><tr><th>경조 구분</th><td>☐ 결혼  ☐ 출산  ☐ 회갑/칠순  ☐ 사망 (본인 가족)  ☐ 기타 (       )</td></tr><tr><th>대상자</th><td>성명:              관계:              </td></tr><tr><th>경조일</th><td>20    년    월    일</td></tr><tr><th>장소</th><td></td></tr><tr><th>신청 금액</th><td>            원</td></tr><tr><th>증빙 서류</th><td>☐ 청첩장  ☐ 사망진단서  ☐ 출생증명서  ☐ 기타</td></tr></table><p><br></p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">신청인:                 (서명)</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-exp-005', '물품구매 요청서', '업무에 필요한 물품 구매를 요청하는 문서', '경비/비용', '<h1 style="text-align:center">물품구매 요청서</h1><p><br></p><table><tr><th>요청일</th><td>20    년    월    일</td><th>요청자</th><td></td></tr><tr><th>부서</th><td></td><th>연락처</th><td></td></tr></table><p><br></p><h2>구매 요청 내역</h2><table><tr><th>No</th><th>품목명</th><th>규격/사양</th><th>수량</th><th>예상 단가</th><th>예상 금액</th></tr><tr><td>1</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>2</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>3</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td colspan="5"><strong>합계</strong></td><td><strong></strong></td></tr></table><p><br></p><table><tr><th>구매 사유</th><td><p><br></p><p><br></p></td></tr><tr><th>희망 납품일</th><td>20    년    월    일까지</td></tr><tr><th>비고</th><td></td></tr></table><p><br></p><table><tr><th>요청자</th><th>팀장</th><th>구매담당</th><th>대표이사</th></tr><tr><td><p><br></p></td><td></td><td></td><td></td></tr></table>', 'admin-001', 1);

-- ============================================
-- 업무/보고 관련
-- ============================================

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-work-001', '업무보고서 (일간/주간/월간)', '일간, 주간, 월간 업무 현황을 보고하는 문서', '업무/보고', '<h1 style="text-align:center">업 무 보 고 서</h1><p><br></p><table><tr><th>보고자</th><td></td><th>부서</th><td></td></tr><tr><th>보고 유형</th><td>☐ 일간  ☐ 주간  ☐ 월간</td><th>보고 기간</th><td>20  년  월  일 ~ 20  년  월  일</td></tr></table><p><br></p><h2>1. 금기 수행 업무</h2><table><tr><th>No</th><th>업무 내용</th><th>진행률</th><th>비고</th></tr><tr><td>1</td><td></td><td>  %</td><td></td></tr><tr><td>2</td><td></td><td>  %</td><td></td></tr><tr><td>3</td><td></td><td>  %</td><td></td></tr><tr><td>4</td><td></td><td>  %</td><td></td></tr></table><p><br></p><h2>2. 주요 성과</h2><p><br></p><p><br></p><h2>3. 이슈 및 건의사항</h2><p><br></p><p><br></p><h2>4. 차기 업무 계획</h2><table><tr><th>No</th><th>업무 내용</th><th>예정일</th><th>비고</th></tr><tr><td>1</td><td></td><td></td><td></td></tr><tr><td>2</td><td></td><td></td><td></td></tr><tr><td>3</td><td></td><td></td><td></td></tr></table><p><br></p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">보고자:                 (서명)</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-work-002', '시말서 / 경위서', '업무상 과실이나 사고에 대한 경위를 보고하는 문서', '업무/보고', '<h1 style="text-align:center">시 말 서</h1><p><br></p><table><tr><th>성명</th><td></td><th>부서</th><td></td></tr><tr><th>직급</th><td></td><th>사번</th><td></td></tr></table><p><br></p><table><tr><th>사건 일시</th><td>20    년    월    일      시    분</td></tr><tr><th>사건 장소</th><td></td></tr><tr><th>사건 개요</th><td><p><br></p><p><br></p></td></tr><tr><th>상세 경위</th><td><p><br></p><p><br></p><p><br></p><p><br></p></td></tr><tr><th>피해/영향 범위</th><td><p><br></p></td></tr><tr><th>조치 사항</th><td><p><br></p><p><br></p></td></tr><tr><th>재발 방지 대책</th><td><p><br></p><p><br></p></td></tr></table><p><br></p><p>위 내용이 사실과 다름없음을 확인하며, 향후 같은 일이 재발하지 않도록 하겠습니다.</p><p><br></p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">작성자:                 (서명)</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-work-003', '사유서 (범용)', '각종 사유를 기재하는 범용 사유서', '업무/보고', '<h1 style="text-align:center">사 유 서</h1><p><br></p><table><tr><th>성명</th><td></td><th>부서</th><td></td></tr><tr><th>직급</th><td></td><th>작성일</th><td>20    년    월    일</td></tr></table><p><br></p><table><tr><th>제목</th><td><p><br></p></td></tr><tr><th>사유 상세</th><td><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p></td></tr><tr><th>첨부 서류</th><td>☐ 있음 (          )  ☐ 없음</td></tr></table><p><br></p><p>위와 같은 사유를 보고드립니다.</p><p><br></p><p style="text-align:center">작성자:                 (서명)</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-work-004', '업무 인수인계서', '퇴직, 부서 이동 등 시 업무를 인수인계하는 문서', '업무/보고', '<h1 style="text-align:center">업무 인수인계서</h1><p><br></p><h2>인계자 / 인수자 정보</h2><table><tr><th></th><th>인계자</th><th>인수자</th></tr><tr><th>성명</th><td></td><td></td></tr><tr><th>부서/직급</th><td></td><td></td></tr><tr><th>연락처</th><td></td><td></td></tr></table><p><br></p><table><tr><th>인계 사유</th><td>☐ 퇴직  ☐ 부서이동  ☐ 휴직  ☐ 기타 (          )</td></tr><tr><th>인계 기간</th><td>20    년    월    일 ~ 20    년    월    일</td></tr></table><p><br></p><h2>인수인계 업무 목록</h2><table><tr><th>No</th><th>업무명</th><th>업무 내용</th><th>관련 파일/시스템</th><th>진행 상태</th><th>특이사항</th></tr><tr><td>1</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>2</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>3</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>4</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>5</td><td></td><td></td><td></td><td></td><td></td></tr></table><p><br></p><h2>주요 계정/접근권한</h2><table><tr><th>시스템/서비스</th><th>계정 정보</th><th>비고</th></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr></table><p><br></p><h2>비고 및 참고사항</h2><p><br></p><p><br></p><p><br></p><p>위와 같이 업무 인수인계를 완료하였음을 확인합니다.</p><p><br></p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">인계자:                 (서명)          인수자:                 (서명)</p><p><br></p><table><tr><th>팀장 확인</th><td><p><br></p></td></tr></table>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-work-005', '제안서 / 기안서', '업무 개선이나 새로운 프로젝트를 제안하는 문서', '업무/보고', '<h1 style="text-align:center">제 안 서</h1><p><br></p><table><tr><th>기안일</th><td>20    년    월    일</td><th>기안자</th><td></td></tr><tr><th>부서</th><td></td><th>직급</th><td></td></tr></table><p><br></p><table><tr><th>제목</th><td colspan="3"><p><br></p></td></tr></table><p><br></p><h2>1. 제안 배경 및 목적</h2><p><br></p><p><br></p><p><br></p><h2>2. 현황 분석</h2><p><br></p><p><br></p><h2>3. 제안 내용</h2><p><br></p><p><br></p><p><br></p><h2>4. 기대 효과</h2><p><br></p><p><br></p><h2>5. 실행 계획</h2><table><tr><th>단계</th><th>내용</th><th>기간</th><th>담당</th></tr><tr><td>1</td><td></td><td></td><td></td></tr><tr><td>2</td><td></td><td></td><td></td></tr><tr><td>3</td><td></td><td></td><td></td></tr></table><p><br></p><h2>6. 소요 예산</h2><table><tr><th>항목</th><th>금액</th><th>비고</th></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td><strong>합계</strong></td><td></td><td></td></tr></table><p><br></p><h2>7. 첨부 자료</h2><p><br></p><p><br></p><table><tr><th>기안자</th><th>팀장</th><th>부서장</th><th>대표이사</th></tr><tr><td><p><br></p><p><br></p></td><td></td><td></td><td></td></tr></table>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-work-006', '회의록', '회의 내용과 결정사항을 기록하는 문서', '업무/보고', '<h1 style="text-align:center">회 의 록</h1><p><br></p><table><tr><th>회의명</th><td colspan="3"></td></tr><tr><th>일시</th><td>20    년    월    일      시    분 ~     시    분</td><th>장소</th><td></td></tr><tr><th>주관</th><td></td><th>작성자</th><td></td></tr><tr><th>참석자</th><td colspan="3"><p><br></p></td></tr></table><p><br></p><h2>1. 안건</h2><p><br></p><p><br></p><h2>2. 회의 내용</h2><p><br></p><p><br></p><p><br></p><p><br></p><h2>3. 결정 사항</h2><table><tr><th>No</th><th>결정 내용</th><th>담당자</th><th>완료 기한</th></tr><tr><td>1</td><td></td><td></td><td></td></tr><tr><td>2</td><td></td><td></td><td></td></tr><tr><td>3</td><td></td><td></td><td></td></tr></table><p><br></p><h2>4. 후속 조치</h2><p><br></p><p><br></p><h2>5. 차기 회의 일정</h2><p>일시:                장소:                </p><p><br></p><p style="text-align:center">20    년    월    일</p><p style="text-align:center">작성자:                 (서명)</p>', 'admin-001', 1);
