-- ============================================
-- 근태/휴가 관련 (10개)
-- ============================================

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-att-001', '연차휴가 신청서', '연차/연차휴가 사용 시 작성', '근태/휴가', '<h1 style="text-align:center;font-size:20px">연 차 휴 가 신 청 서</h1><p><br></p><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">부 서</th><td style="width:35%"></td></tr><tr><th>직 급</th><td></td><th>사 번</th><td></td></tr></table><p><br></p><table><tr><th style="width:15%">휴가 종류</th><td>☐ 연차 &nbsp; ☐ 하계휴가 &nbsp; ☐ 경조휴가 &nbsp; ☐ 기타 ( &nbsp; &nbsp; &nbsp; &nbsp; )</td></tr><tr><th>휴가 기간</th><td>&nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일 ~ &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일 (총 &nbsp; &nbsp; 일간)</td></tr><tr><th>잔여 연차</th><td>총 &nbsp; &nbsp; 일 중 &nbsp; &nbsp; 일 사용 / &nbsp; &nbsp; 일 잔여</td></tr><tr><th>휴가 사유</th><td style="height:60px"></td></tr><tr><th>비상연락처</th><td></td></tr><tr><th>업무대행자</th><td>부서: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 성명: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</td></tr></table><p><br></p><p style="text-align:center;font-size:13px">위와 같이 휴가를 신청하오니 허가하여 주시기 바랍니다.</p><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-att-002', '반차 신청서', '오전/오후 반차 사용 시 작성', '근태/휴가', '<h1 style="text-align:center;font-size:20px">반 차 신 청 서</h1><p><br></p><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">부 서</th><td style="width:35%"></td></tr><tr><th>직 급</th><td></td><th>사 번</th><td></td></tr></table><p><br></p><table><tr><th style="width:15%">반차 구분</th><td>☐ 오전 반차 (09:00~13:00) &nbsp; ☐ 오후 반차 (14:00~18:00)</td></tr><tr><th>반차 일자</th><td>&nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일 ( &nbsp; &nbsp; 요일)</td></tr><tr><th>사 유</th><td style="height:60px"></td></tr><tr><th>비상연락처</th><td></td></tr></table><p><br></p><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-att-003', '지각/조퇴/외출 사유서', '지각, 조퇴, 외출 시 사유 기재', '근태/휴가', '<h1 style="text-align:center;font-size:20px">지각 / 조퇴 / 외출 사유서</h1><p><br></p><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">부 서</th><td style="width:35%"></td></tr><tr><th>직 급</th><td></td><th>사 번</th><td></td></tr></table><p><br></p><table><tr><th style="width:15%">구 분</th><td>☐ 지각 &nbsp; ☐ 조퇴 &nbsp; ☐ 외출</td></tr><tr><th>일 시</th><td>&nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일 &nbsp; &nbsp; 시 &nbsp; &nbsp; 분 ~ &nbsp; &nbsp; 시 &nbsp; &nbsp; 분</td></tr><tr><th>사 유</th><td style="height:80px"></td></tr><tr><th>증빙서류</th><td>☐ 있음 (첨부) &nbsp; ☐ 없음</td></tr></table><p><br></p><p style="text-align:center;font-size:13px">위와 같은 사유로 보고드리오니 양해하여 주시기 바랍니다.</p><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-att-004', '결근 사유서', '결근 발생 시 사유 기재', '근태/휴가', '<h1 style="text-align:center;font-size:20px">결 근 사 유 서</h1><p><br></p><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">부 서</th><td style="width:35%"></td></tr><tr><th>직 급</th><td></td><th>사 번</th><td></td></tr></table><p><br></p><table><tr><th style="width:15%">결근 일자</th><td>&nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일 ~ &nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일 (총 &nbsp; &nbsp; 일)</td></tr><tr><th>결근 사유</th><td style="height:100px"></td></tr><tr><th>증빙서류</th><td>☐ 진단서 &nbsp; ☐ 기타 ( &nbsp; &nbsp; &nbsp; &nbsp; ) &nbsp; ☐ 없음</td></tr><tr><th>향후 계획</th><td style="height:60px"></td></tr></table><p><br></p><p style="text-align:center;font-size:13px">위와 같은 사유로 결근하였기에 사유서를 제출합니다.</p><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-att-005', '휴직 신청서', '육아휴직, 병가휴직 등 휴직 시 작성', '근태/휴가', '<h1 style="text-align:center;font-size:20px">휴 직 신 청 서</h1><p><br></p><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">부 서</th><td style="width:35%"></td></tr><tr><th>직 급</th><td></td><th>사 번</th><td></td></tr><tr><th>입사일</th><td></td><th>연락처</th><td></td></tr></table><p><br></p><table><tr><th style="width:15%">휴직 유형</th><td>☐ 육아휴직 &nbsp; ☐ 병가휴직 &nbsp; ☐ 개인사유 &nbsp; ☐ 기타 ( &nbsp; &nbsp; &nbsp; )</td></tr><tr><th>휴직 기간</th><td>&nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일 ~ &nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일 (총 &nbsp; &nbsp; 개월)</td></tr><tr><th>휴직 사유</th><td style="height:80px"></td></tr><tr><th>첨부 서류</th><td>☐ 진단서 &nbsp; ☐ 출생증명서 &nbsp; ☐ 기타 ( &nbsp; &nbsp; &nbsp; &nbsp; )</td></tr><tr><th>업무인수자</th><td>부서: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 성명: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</td></tr></table><p><br></p><p style="text-align:center;font-size:13px">위와 같이 휴직을 신청하오니 승인하여 주시기 바랍니다.</p><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-att-006', '복직 신청서', '휴직 후 복직 시 작성', '근태/휴가', '<h1 style="text-align:center;font-size:20px">복 직 신 청 서</h1><p><br></p><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">부 서</th><td style="width:35%"></td></tr><tr><th>직 급</th><td></td><th>사 번</th><td></td></tr></table><p><br></p><table><tr><th style="width:15%">휴직 기간</th><td>&nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일 ~ &nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일</td></tr><tr><th>휴직 유형</th><td></td></tr><tr><th>복직 예정일</th><td>&nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</td></tr><tr><th>복직 사유</th><td style="height:60px"></td></tr><tr><th>건강 상태</th><td>☐ 양호 &nbsp; ☐ 치료 중 (상세: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; )</td></tr></table><p><br></p><p style="text-align:center;font-size:13px">위와 같이 복직을 신청하오니 승인하여 주시기 바랍니다.</p><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-att-007', '출장 신청서', '국내/해외 출장 시 사전 승인용', '근태/휴가', '<h1 style="text-align:center;font-size:20px">출 장 신 청 서</h1><p><br></p><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">부 서</th><td style="width:35%"></td></tr><tr><th>직 급</th><td></td><th>사 번</th><td></td></tr></table><p><br></p><table><tr><th style="width:15%">출장 구분</th><td>☐ 국내 출장 &nbsp; ☐ 해외 출장</td></tr><tr><th>출장 기간</th><td>&nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일 ~ &nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일 ( &nbsp; 박 &nbsp; 일)</td></tr><tr><th>출장지</th><td></td></tr><tr><th>출장 목적</th><td style="height:60px"></td></tr><tr><th>동행자</th><td></td></tr><tr><th>예상 경비</th><td>교통비: &nbsp; &nbsp; &nbsp; &nbsp; 원 / 숙박비: &nbsp; &nbsp; &nbsp; &nbsp; 원 / 기타: &nbsp; &nbsp; &nbsp; &nbsp; 원 / 합계: &nbsp; &nbsp; &nbsp; &nbsp; 원</td></tr><tr><th>업무대행자</th><td></td></tr></table><p><br></p><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-att-008', '출장 보고서', '출장 완료 후 결과 보고', '근태/휴가', '<h1 style="text-align:center;font-size:20px">출 장 보 고 서</h1><p><br></p><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">부 서</th><td style="width:35%"></td></tr><tr><th>출장 기간</th><td colspan="3">&nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일 ~ &nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일</td></tr><tr><th>출장지</th><td></td><th>출장 목적</th><td></td></tr></table><p><br></p><h2 style="font-size:15px">출장 내용</h2><table><tr><th style="width:15%">일자</th><th style="width:25%">방문처</th><th style="width:60%">주요 활동 내용</th></tr><tr><td></td><td></td><td style="height:40px"></td></tr><tr><td></td><td></td><td style="height:40px"></td></tr></table><p><br></p><h2 style="font-size:15px">출장 성과 및 결과</h2><p style="min-height:60px"><br></p><h2 style="font-size:15px">후속 조치 사항</h2><p style="min-height:60px"><br></p><h2 style="font-size:15px">경비 정산</h2><table><tr><th>항목</th><th>금액</th><th>비고</th></tr><tr><td>교통비</td><td></td><td></td></tr><tr><td>숙박비</td><td></td><td></td></tr><tr><td>식비</td><td></td><td></td></tr><tr><td>기타</td><td></td><td></td></tr><tr><td><strong>합계</strong></td><td></td><td></td></tr></table><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-att-009', '재택근무 신청서', '재택근무 사전 승인용', '근태/휴가', '<h1 style="text-align:center;font-size:20px">재택근무 신청서</h1><p><br></p><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">부 서</th><td style="width:35%"></td></tr><tr><th>직 급</th><td></td><th>사 번</th><td></td></tr></table><p><br></p><table><tr><th style="width:15%">근무 일자</th><td>&nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일 ( &nbsp; &nbsp; 요일)</td></tr><tr><th>근무 시간</th><td>&nbsp; &nbsp; 시 &nbsp; &nbsp; 분 ~ &nbsp; &nbsp; 시 &nbsp; &nbsp; 분</td></tr><tr><th>근무 장소</th><td>☐ 자택 &nbsp; ☐ 기타 ( &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; )</td></tr><tr><th>신청 사유</th><td style="height:60px"></td></tr><tr><th>업무 계획</th><td style="height:80px"></td></tr><tr><th>연락 수단</th><td>전화: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; / 메신저: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</td></tr></table><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-att-010', '초과근무(야근) 신청서', '야근/휴일근무 등 초과근무 시 작성', '근태/휴가', '<h1 style="text-align:center;font-size:20px">초과근무 신청서</h1><p><br></p><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">부 서</th><td style="width:35%"></td></tr><tr><th>직 급</th><td></td><th>사 번</th><td></td></tr></table><p><br></p><table><tr><th style="width:15%">근무 구분</th><td>☐ 연장근무(야근) &nbsp; ☐ 휴일근무 &nbsp; ☐ 야간근무</td></tr><tr><th>근무 일시</th><td>&nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일 &nbsp; &nbsp; 시 &nbsp; &nbsp; 분 ~ &nbsp; &nbsp; 시 &nbsp; &nbsp; 분 ( &nbsp; &nbsp; 시간)</td></tr><tr><th>사 유</th><td style="height:60px"></td></tr><tr><th>업무 내용</th><td style="height:60px"></td></tr><tr><th>보상 희망</th><td>☐ 수당 지급 &nbsp; ☐ 대체 휴가</td></tr></table><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

-- ============================================
-- 인사/채용 관련 (7개)
-- ============================================

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-hr-001', '입사지원서', '채용 지원 시 작성', '인사/채용', '<h1 style="text-align:center;font-size:20px">입 사 지 원 서</h1><p><br></p><h2 style="font-size:15px">인적사항</h2><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">생년월일</th><td style="width:35%"></td></tr><tr><th>연락처</th><td></td><th>이메일</th><td></td></tr><tr><th>주 소</th><td colspan="3"></td></tr><tr><th>지원 부서</th><td></td><th>희망 연봉</th><td></td></tr></table><p><br></p><h2 style="font-size:15px">학력사항</h2><table><tr><th style="width:20%">기간</th><th style="width:30%">학교명</th><th style="width:25%">전공</th><th style="width:25%">학위</th></tr><tr><td></td><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td><td></td></tr></table><p><br></p><h2 style="font-size:15px">경력사항</h2><table><tr><th style="width:20%">기간</th><th style="width:25%">회사명</th><th style="width:20%">부서/직급</th><th style="width:35%">담당 업무</th></tr><tr><td></td><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td><td></td></tr></table><p><br></p><h2 style="font-size:15px">자격/면허</h2><table><tr><th style="width:25%">취득일</th><th style="width:40%">자격증명</th><th style="width:35%">발행기관</th></tr><tr><td></td><td></td><td></td></tr></table><p><br></p><h2 style="font-size:15px">자기소개</h2><p style="min-height:120px"><br></p><p style="text-align:center;font-size:13px">위 기재 사항은 사실과 다름이 없음을 확인합니다.</p><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-hr-002', '경력증명서 발급 신청서', '경력증명서 발급 요청', '인사/채용', '<h1 style="text-align:center;font-size:20px">경력증명서 발급 신청서</h1><p><br></p><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">부 서</th><td style="width:35%"></td></tr><tr><th>직 급</th><td></td><th>사 번</th><td></td></tr><tr><th>재직 기간</th><td colspan="3">&nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일 ~ &nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일</td></tr></table><p><br></p><table><tr><th style="width:15%">발급 사유</th><td style="height:40px"></td></tr><tr><th>제출처</th><td></td></tr><tr><th>필요 부수</th><td>&nbsp; &nbsp; 부</td></tr><tr><th>기재 희망</th><td>☐ 직급 &nbsp; ☐ 업무내용 &nbsp; ☐ 연봉 &nbsp; ☐ 기타 ( &nbsp; &nbsp; &nbsp; &nbsp; )</td></tr></table><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-hr-003', '재직증명서 발급 신청서', '재직증명서 발급 요청', '인사/채용', '<h1 style="text-align:center;font-size:20px">재직증명서 발급 신청서</h1><p><br></p><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">부 서</th><td style="width:35%"></td></tr><tr><th>직 급</th><td></td><th>사 번</th><td></td></tr><tr><th>입사일</th><td></td><th>연락처</th><td></td></tr></table><p><br></p><table><tr><th style="width:15%">발급 사유</th><td>☐ 금융기관 &nbsp; ☐ 관공서 &nbsp; ☐ 비자 신청 &nbsp; ☐ 기타 ( &nbsp; &nbsp; &nbsp; &nbsp; )</td></tr><tr><th>제출처</th><td></td></tr><tr><th>필요 부수</th><td>&nbsp; &nbsp; 부</td></tr></table><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-hr-004', '퇴직원 (사직서)', '자발적 퇴직 의사 전달', '인사/채용', '<h1 style="text-align:center;font-size:20px">퇴 직 원</h1><p><br></p><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">부 서</th><td style="width:35%"></td></tr><tr><th>직 급</th><td></td><th>사 번</th><td></td></tr><tr><th>입사일</th><td></td><th>연락처</th><td></td></tr></table><p><br></p><table><tr><th style="width:15%">퇴직 희망일</th><td>&nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</td></tr><tr><th>퇴직 사유</th><td style="height:100px"></td></tr><tr><th>인수인계</th><td style="height:60px"></td></tr><tr><th>인수 대상자</th><td></td></tr></table><p><br></p><p style="text-align:center;font-size:13px">위와 같은 사유로 퇴직하고자 하오니 허가하여 주시기 바랍니다.</p><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-hr-005', '인사발령 통보서', '인사이동, 승진, 전보 등 통보', '인사/채용', '<h1 style="text-align:center;font-size:20px">인사발령 통보서</h1><p><br></p><p style="text-align:center;font-size:14px">다음과 같이 인사발령을 통보합니다.</p><p><br></p><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">사 번</th><td style="width:35%"></td></tr></table><p><br></p><table><tr><th style="width:15%">발령 구분</th><td>☐ 승진 &nbsp; ☐ 전보 &nbsp; ☐ 전직 &nbsp; ☐ 파견 &nbsp; ☐ 기타</td></tr><tr><th>발령일자</th><td>&nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</td></tr><tr><th>현 소속</th><td>부서: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 직급: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</td></tr><tr><th>변경 소속</th><td>부서: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 직급: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</td></tr><tr><th>발령 사유</th><td style="height:60px"></td></tr></table><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-hr-006', '서약서', '비밀유지, 경업금지 등 서약', '인사/채용', '<h1 style="text-align:center;font-size:20px">서 약 서</h1><p><br></p><p style="font-size:13px">본인은 회사에 재직하는 동안 및 퇴직 후에도 아래 사항을 준수할 것을 서약합니다.</p><p><br></p><h2 style="font-size:14px">제1조 (비밀유지 의무)</h2><p style="font-size:13px">본인은 업무 수행 과정에서 취득한 회사의 영업비밀, 기술정보, 고객정보, 경영정보 등 일체의 비밀정보를 재직 중은 물론 퇴직 후에도 제3자에게 누설하거나 무단으로 사용하지 않겠습니다.</p><p><br></p><h2 style="font-size:14px">제2조 (경업금지 의무)</h2><p style="font-size:13px">본인은 퇴직 후 &nbsp; &nbsp; 년간 회사와 동종 또는 유사한 업종의 사업체에 취업하거나 스스로 동종 영업을 하지 않겠습니다.</p><p><br></p><h2 style="font-size:14px">제3조 (손해배상)</h2><p style="font-size:13px">본인이 위 의무를 위반하여 회사에 손해를 끼친 경우, 그에 대한 손해배상 책임을 지겠습니다.</p><p><br></p><table><tr><th style="width:15%">성 명</th><td style="width:85%"></td></tr><tr><th>부서/직급</th><td></td></tr><tr><th>주 소</th><td></td></tr></table><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-hr-007', '신원보증서', '입사 시 제출하는 신원보증서', '인사/채용', '<h1 style="text-align:center;font-size:20px">신 원 보 증 서</h1><p><br></p><h2 style="font-size:15px">피보증인 (입사자)</h2><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">생년월일</th><td style="width:35%"></td></tr><tr><th>주 소</th><td colspan="3"></td></tr></table><p><br></p><h2 style="font-size:15px">보증인</h2><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">관 계</th><td style="width:35%"></td></tr><tr><th>생년월일</th><td></td><th>연락처</th><td></td></tr><tr><th>주 소</th><td colspan="3"></td></tr><tr><th>직 업</th><td></td><th>근무처</th><td></td></tr></table><p><br></p><p style="font-size:13px">본인은 위 피보증인의 신원을 보증하며, 피보증인이 귀사에 재직하는 동안 고의 또는 과실로 귀사에 손해를 끼친 경우 연대하여 배상할 것을 보증합니다.</p><p style="font-size:13px">보증 기간: 입사일로부터 &nbsp; &nbsp; 년간</p><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

-- ============================================
-- 경비/비용 관련 (5개)
-- ============================================

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-exp-001', '지출결의서', '비용 지출 승인용 결의서', '경비/비용', '<h1 style="text-align:center;font-size:20px">지 출 결 의 서</h1><p><br></p><table><tr><th style="width:15%">기안일</th><td style="width:35%">&nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일</td><th style="width:15%">기안자</th><td style="width:35%"></td></tr><tr><th>부 서</th><td></td><th>직 급</th><td></td></tr></table><p><br></p><table><tr><th style="width:15%">지출 목적</th><td colspan="3" style="height:40px"></td></tr><tr><th>지출 예정일</th><td>&nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일</td><th style="width:15%">지급 방법</th><td>☐ 계좌이체 &nbsp; ☐ 법인카드 &nbsp; ☐ 현금</td></tr></table><p><br></p><h2 style="font-size:15px">지출 내역</h2><table><tr><th style="width:8%">번호</th><th style="width:42%">항목</th><th style="width:25%">금액</th><th style="width:25%">비고</th></tr><tr><td style="text-align:center">1</td><td></td><td></td><td></td></tr><tr><td style="text-align:center">2</td><td></td><td></td><td></td></tr><tr><td style="text-align:center">3</td><td></td><td></td><td></td></tr><tr><td colspan="2" style="text-align:center"><strong>합 계</strong></td><td><strong></strong></td><td></td></tr></table><p><br></p><p style="text-align:center;font-size:13px">위와 같이 지출하고자 결의하오니 승인하여 주시기 바랍니다.</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-exp-002', '법인카드 사용 내역서', '법인카드 사용 내역 보고', '경비/비용', '<h1 style="text-align:center;font-size:20px">법인카드 사용 내역서</h1><p><br></p><table><tr><th style="width:15%">사용자</th><td style="width:35%"></td><th style="width:15%">부 서</th><td style="width:35%"></td></tr><tr><th>카드번호</th><td>****-****-****- &nbsp; &nbsp; &nbsp;</td><th>보고 기간</th><td>&nbsp; &nbsp; 년 &nbsp; &nbsp; 월</td></tr></table><p><br></p><table><tr><th style="width:5%">No</th><th style="width:12%">사용일</th><th style="width:18%">가맹점명</th><th style="width:25%">사용 목적</th><th style="width:15%">금액</th><th style="width:25%">참석자</th></tr><tr><td style="text-align:center">1</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td style="text-align:center">2</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td style="text-align:center">3</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td style="text-align:center">4</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td colspan="4" style="text-align:center"><strong>합 계</strong></td><td><strong></strong></td><td></td></tr></table><p style="font-size:12px;color:#666">※ 영수증은 별도 첨부</p><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-exp-003', '교통비/출장비 정산서', '교통비, 출장비 정산', '경비/비용', '<h1 style="text-align:center;font-size:20px">교통비 / 출장비 정산서</h1><p><br></p><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">부 서</th><td style="width:35%"></td></tr><tr><th>정산 기간</th><td colspan="3">&nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일 ~ &nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일</td></tr></table><p><br></p><table><tr><th style="width:5%">No</th><th style="width:12%">일자</th><th style="width:28%">출발지 → 도착지</th><th style="width:15%">교통수단</th><th style="width:15%">금액</th><th style="width:25%">비고</th></tr><tr><td style="text-align:center">1</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td style="text-align:center">2</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td style="text-align:center">3</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td colspan="4" style="text-align:center"><strong>합 계</strong></td><td><strong></strong></td><td></td></tr></table><p style="font-size:12px;color:#666">※ 영수증 및 증빙 자료를 첨부해 주시기 바랍니다.</p><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-exp-004', '경조사비 신청서', '경조사 발생 시 경조금 신청', '경비/비용', '<h1 style="text-align:center;font-size:20px">경조사비 신청서</h1><p><br></p><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">부 서</th><td style="width:35%"></td></tr><tr><th>직 급</th><td></td><th>사 번</th><td></td></tr></table><p><br></p><table><tr><th style="width:15%">경조 구분</th><td>☐ 결혼 &nbsp; ☐ 출산 &nbsp; ☐ 회갑/칠순 &nbsp; ☐ 사망 &nbsp; ☐ 기타 ( &nbsp; &nbsp; &nbsp; )</td></tr><tr><th>대상자</th><td>성명: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 관계: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</td></tr><tr><th>경조일</th><td>&nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</td></tr><tr><th>장 소</th><td></td></tr><tr><th>신청 금액</th><td>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 원</td></tr><tr><th>증빙 서류</th><td>☐ 청첩장 &nbsp; ☐ 사망진단서 &nbsp; ☐ 출생증명서 &nbsp; ☐ 기타</td></tr></table><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-exp-005', '물품구매 요청서', '업무 물품 구매 요청', '경비/비용', '<h1 style="text-align:center;font-size:20px">물품구매 요청서</h1><p><br></p><table><tr><th style="width:15%">요청일</th><td style="width:35%">&nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일</td><th style="width:15%">요청자</th><td style="width:35%"></td></tr><tr><th>부 서</th><td></td><th>연락처</th><td></td></tr></table><p><br></p><h2 style="font-size:15px">구매 요청 내역</h2><table><tr><th style="width:5%">No</th><th style="width:25%">품목명</th><th style="width:20%">규격/사양</th><th style="width:10%">수량</th><th style="width:18%">예상 단가</th><th style="width:22%">예상 금액</th></tr><tr><td style="text-align:center">1</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td style="text-align:center">2</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td colspan="5" style="text-align:center"><strong>합 계</strong></td><td><strong></strong></td></tr></table><p><br></p><table><tr><th style="width:15%">구매 사유</th><td style="height:60px"></td></tr><tr><th>납품 희망일</th><td>&nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일까지</td></tr><tr><th>비 고</th><td></td></tr></table>', 'admin-001', 1);

-- ============================================
-- 업무/보고 관련 (6개)
-- ============================================

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-work-001', '업무보고서', '일간/주간/월간 업무 보고', '업무/보고', '<h1 style="text-align:center;font-size:20px">업 무 보 고 서</h1><p><br></p><table><tr><th style="width:15%">보고자</th><td style="width:35%"></td><th style="width:15%">부 서</th><td style="width:35%"></td></tr><tr><th>보고 유형</th><td>☐ 일간 &nbsp; ☐ 주간 &nbsp; ☐ 월간</td><th>보고 기간</th><td>&nbsp; &nbsp; 월 &nbsp; &nbsp; 일 ~ &nbsp; &nbsp; 월 &nbsp; &nbsp; 일</td></tr></table><p><br></p><h2 style="font-size:15px">1. 금기 수행 업무</h2><table><tr><th style="width:5%">No</th><th style="width:55%">업무 내용</th><th style="width:15%">진행률</th><th style="width:25%">비고</th></tr><tr><td style="text-align:center">1</td><td></td><td style="text-align:center">&nbsp; %</td><td></td></tr><tr><td style="text-align:center">2</td><td></td><td style="text-align:center">&nbsp; %</td><td></td></tr><tr><td style="text-align:center">3</td><td></td><td style="text-align:center">&nbsp; %</td><td></td></tr></table><p><br></p><h2 style="font-size:15px">2. 주요 성과</h2><p style="min-height:60px"><br></p><h2 style="font-size:15px">3. 이슈 및 건의사항</h2><p style="min-height:60px"><br></p><h2 style="font-size:15px">4. 차기 업무 계획</h2><table><tr><th style="width:5%">No</th><th style="width:55%">업무 내용</th><th style="width:20%">예정일</th><th style="width:20%">비고</th></tr><tr><td style="text-align:center">1</td><td></td><td></td><td></td></tr><tr><td style="text-align:center">2</td><td></td><td></td><td></td></tr></table><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-work-002', '시말서 / 경위서', '업무상 과실이나 사고 경위 보고', '업무/보고', '<h1 style="text-align:center;font-size:20px">시 말 서</h1><p><br></p><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">부 서</th><td style="width:35%"></td></tr><tr><th>직 급</th><td></td><th>사 번</th><td></td></tr></table><p><br></p><table><tr><th style="width:15%">사건 일시</th><td>&nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일 &nbsp; &nbsp; 시 &nbsp; &nbsp; 분</td></tr><tr><th>사건 장소</th><td></td></tr><tr><th>사건 개요</th><td style="height:60px"></td></tr><tr><th>상세 경위</th><td style="height:120px"></td></tr><tr><th>피해/영향</th><td style="height:60px"></td></tr><tr><th>조치 사항</th><td style="height:60px"></td></tr><tr><th>재발 방지</th><td style="height:60px"></td></tr></table><p><br></p><p style="text-align:center;font-size:13px">위 내용이 사실과 다름없음을 확인하며, 향후 같은 일이 재발하지 않도록 하겠습니다.</p><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-work-003', '사유서 (범용)', '각종 사유 기재용 범용 사유서', '업무/보고', '<h1 style="text-align:center;font-size:20px">사 유 서</h1><p><br></p><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">부 서</th><td style="width:35%"></td></tr><tr><th>직 급</th><td></td><th>작성일</th><td>&nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일</td></tr></table><p><br></p><table><tr><th style="width:15%">제 목</th><td style="height:30px"></td></tr><tr><th>사유 상세</th><td style="height:200px"></td></tr><tr><th>첨부 서류</th><td>☐ 있음 ( &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ) &nbsp; ☐ 없음</td></tr></table><p><br></p><p style="text-align:center;font-size:13px">위와 같은 사유를 보고드립니다.</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-work-004', '업무 인수인계서', '퇴직, 부서이동 등 업무 인수인계', '업무/보고', '<h1 style="text-align:center;font-size:20px">업무 인수인계서</h1><p><br></p><h2 style="font-size:15px">인계자 / 인수자 정보</h2><table><tr><th style="width:15%"></th><th style="width:42%">인계자</th><th style="width:43%">인수자</th></tr><tr><th>성 명</th><td></td><td></td></tr><tr><th>부서/직급</th><td></td><td></td></tr><tr><th>연락처</th><td></td><td></td></tr></table><p><br></p><table><tr><th style="width:15%">인계 사유</th><td>☐ 퇴직 &nbsp; ☐ 부서이동 &nbsp; ☐ 휴직 &nbsp; ☐ 기타 ( &nbsp; &nbsp; &nbsp; &nbsp; )</td></tr><tr><th>인계 기간</th><td>&nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일 ~ &nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일</td></tr></table><p><br></p><h2 style="font-size:15px">인수인계 업무 목록</h2><table><tr><th style="width:5%">No</th><th style="width:15%">업무명</th><th style="width:30%">업무 내용</th><th style="width:20%">관련 파일</th><th style="width:12%">진행상태</th><th style="width:18%">특이사항</th></tr><tr><td style="text-align:center">1</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td style="text-align:center">2</td><td></td><td></td><td></td><td></td><td></td></tr><tr><td style="text-align:center">3</td><td></td><td></td><td></td><td></td><td></td></tr></table><p><br></p><h2 style="font-size:15px">비고 및 참고사항</h2><p style="min-height:60px"><br></p><p style="text-align:center;font-size:13px">위와 같이 업무 인수인계를 완료하였음을 확인합니다.</p><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-work-005', '제안서 / 기안서', '업무 개선이나 프로젝트 제안', '업무/보고', '<h1 style="text-align:center;font-size:20px">제 안 서</h1><p><br></p><table><tr><th style="width:15%">기안일</th><td style="width:35%">&nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일</td><th style="width:15%">기안자</th><td style="width:35%"></td></tr><tr><th>부 서</th><td></td><th>직 급</th><td></td></tr></table><p><br></p><table><tr><th style="width:15%">제 목</th><td colspan="3" style="height:30px"></td></tr></table><p><br></p><h2 style="font-size:15px">1. 제안 배경 및 목적</h2><p style="min-height:80px"><br></p><h2 style="font-size:15px">2. 현황 분석</h2><p style="min-height:60px"><br></p><h2 style="font-size:15px">3. 제안 내용</h2><p style="min-height:80px"><br></p><h2 style="font-size:15px">4. 기대 효과</h2><p style="min-height:60px"><br></p><h2 style="font-size:15px">5. 실행 계획</h2><table><tr><th style="width:10%">단계</th><th style="width:40%">내용</th><th style="width:25%">기간</th><th style="width:25%">담당</th></tr><tr><td style="text-align:center">1</td><td></td><td></td><td></td></tr><tr><td style="text-align:center">2</td><td></td><td></td><td></td></tr></table><p><br></p><h2 style="font-size:15px">6. 소요 예산</h2><table><tr><th style="width:40%">항목</th><th style="width:30%">금액</th><th style="width:30%">비고</th></tr><tr><td></td><td></td><td></td></tr><tr><td><strong>합 계</strong></td><td></td><td></td></tr></table>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-work-007', '외근 보고서', '외근 활동 내용 및 결과 보고', '업무/보고', '<h1 style="text-align:center;font-size:20px">외 근 보 고 서</h1><p><br></p><table><tr><th style="width:15%">성 명</th><td style="width:35%"></td><th style="width:15%">부 서</th><td style="width:35%"></td></tr><tr><th>직 급</th><td></td><th>사 번</th><td></td></tr></table><p><br></p><table><tr><th style="width:15%">외근 일자</th><td>&nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일 ( &nbsp; &nbsp; 요일)</td></tr><tr><th>외근 시간</th><td>&nbsp; &nbsp; 시 &nbsp; &nbsp; 분 ~ &nbsp; &nbsp; 시 &nbsp; &nbsp; 분 (총 &nbsp; &nbsp; 시간)</td></tr><tr><th>외근 장소</th><td></td></tr><tr><th>방문 대상</th><td>업체명: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; / 담당자: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; / 연락처: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</td></tr></table><p><br></p><h2 style="font-size:15px">외근 목적</h2><p style="min-height:60px"><br></p><h2 style="font-size:15px">활동 내용</h2><table><tr><th style="width:15%">시간</th><th style="width:25%">방문처/장소</th><th style="width:60%">활동 내용</th></tr><tr><td></td><td></td><td style="height:40px"></td></tr><tr><td></td><td></td><td style="height:40px"></td></tr><tr><td></td><td></td><td style="height:40px"></td></tr></table><p><br></p><h2 style="font-size:15px">활동 시간</h2><table><tr><th style="width:20%">출발 시간</th><td style="width:30%">&nbsp; &nbsp; 시 &nbsp; &nbsp; 분</td><th style="width:20%">복귀 시간</th><td style="width:30%">&nbsp; &nbsp; 시 &nbsp; &nbsp; 분</td></tr><tr><th>총 활동 시간</th><td colspan="3">&nbsp; &nbsp; &nbsp; 시간 &nbsp; &nbsp; &nbsp; 분</td></tr></table><p><br></p><p style="text-align:center;font-size:13px">위와 같이 외근 결과를 보고합니다.</p><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);

INSERT INTO templates (id, title, description, category, content, created_by, is_active) VALUES
('tpl-work-006', '회의록', '회의 내용과 결정사항 기록', '업무/보고', '<h1 style="text-align:center;font-size:20px">회 의 록</h1><p><br></p><table><tr><th style="width:15%">회의명</th><td colspan="3"></td></tr><tr><th>일 시</th><td style="width:35%">&nbsp; &nbsp; 년 &nbsp; &nbsp; 월 &nbsp; &nbsp; 일 &nbsp; &nbsp; 시 &nbsp; &nbsp; 분 ~ &nbsp; &nbsp; 시 &nbsp; &nbsp; 분</td><th style="width:15%">장 소</th><td style="width:35%"></td></tr><tr><th>주 관</th><td></td><th>작성자</th><td></td></tr><tr><th>참석자</th><td colspan="3" style="height:30px"></td></tr></table><p><br></p><h2 style="font-size:15px">1. 안건</h2><p style="min-height:40px"><br></p><h2 style="font-size:15px">2. 회의 내용</h2><p style="min-height:120px"><br></p><h2 style="font-size:15px">3. 결정 사항</h2><table><tr><th style="width:5%">No</th><th style="width:50%">결정 내용</th><th style="width:20%">담당자</th><th style="width:25%">완료 기한</th></tr><tr><td style="text-align:center">1</td><td></td><td></td><td></td></tr><tr><td style="text-align:center">2</td><td></td><td></td><td></td></tr></table><p><br></p><h2 style="font-size:15px">4. 후속 조치</h2><p style="min-height:40px"><br></p><h2 style="font-size:15px">5. 차기 회의</h2><p style="font-size:13px">일시: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 장소: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p><p style="text-align:center;font-size:13px">&nbsp; &nbsp; &nbsp; &nbsp; 년 &nbsp; &nbsp; &nbsp; 월 &nbsp; &nbsp; &nbsp; 일</p>', 'admin-001', 1);
